name: 'ci/cd process'

on:
  push:
    branches: [ 'main' ]
    
jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/abelopezpaniagua/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build src/Practice.Devops.NugetRegistry/Practice.Devops.NugetRegistry.sln --configuration Release --nowarn:0
    
  
